name = "katelya-tgbed"
compatibility_date = "2024-01-01"

# This is a Cloudflare Pages project
# All backend logic is in /functions directory
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "img_url"
id = "a495728270f448c490c736ad13af2a05"

